##  Trainning Pipeline

#### Today objective
1. building a simple neural network* 
2. dataset:- Breast canceer dataset*
3. main goal:- code to create a neural network

### Steps to Follow

1. Load the dataset
2. Basic Preprocessing
3. Training Process
   1. Creating the model
   2. Forward pass
   3. Loss calculation
   4. Backpropagation
   5. Parameter update
4. Model Evaluation

In [74]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [75]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [76]:
df.size

18777

In [77]:
df.shape

(569, 33)

In [78]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [79]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [80]:
#train test split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [81]:
#scaling
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

In [82]:
x_train

array([[ 0.66029743, -0.24512934,  0.58944388, ..., -0.37277611,
        -0.8699323 , -1.08680799],
       [-0.65522869, -0.43758899, -0.68601848, ..., -0.37022533,
         0.29445979, -0.78921475],
       [ 1.91641269,  0.97687353,  1.91582617, ...,  1.41682163,
         0.33563348, -0.32346473],
       ...,
       [-0.35534532, -0.69961238, -0.39897785, ..., -0.50601689,
         0.16764481, -0.82129729],
       [ 2.10596161,  0.68006828,  2.14168074, ...,  1.89246721,
         1.49179083,  0.9050754 ],
       [-0.45436342, -0.06426364, -0.42402718, ..., -0.35146958,
        -1.31954905, -0.68909509]], shape=(455, 30))

In [83]:
y_train

363    B
293    B
250    M
168    M
439    B
      ..
405    B
313    B
195    B
393    M
355    B
Name: diagnosis, Length: 455, dtype: object

In [84]:
#Label Encoding
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [85]:
y_train

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0])

In [86]:
type(y_train)

numpy.ndarray

In [87]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1])

In [88]:
# Numpy arrays to Pytorch tensors
x_train_tensor=torch.from_numpy(x_train).float()
x_test_tensor=torch.from_numpy(x_test).float()

y_train_tensor=torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor=torch.from_numpy(y_test).float().unsqueeze(1)

In [89]:
x_train_tensor

tensor([[ 0.6603, -0.2451,  0.5894,  ..., -0.3728, -0.8699, -1.0868],
        [-0.6552, -0.4376, -0.6860,  ..., -0.3702,  0.2945, -0.7892],
        [ 1.9164,  0.9769,  1.9158,  ...,  1.4168,  0.3356, -0.3235],
        ...,
        [-0.3553, -0.6996, -0.3990,  ..., -0.5060,  0.1676, -0.8213],
        [ 2.1060,  0.6801,  2.1417,  ...,  1.8925,  1.4918,  0.9051],
        [-0.4544, -0.0643, -0.4240,  ..., -0.3515, -1.3195, -0.6891]])

# defineing the model

In [90]:
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()
        
        
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

    # def loss_function(self, y_pred, y):
        
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        # print(f"epoch {loss}")
        return loss

In [91]:
loss_function=nn.BCELoss()

### Impotrant Parameter

In [92]:
learning_rate=0.1
epochs=25

## Trainign pipeline

In [93]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [94]:
# create model 
model=MySimpleNN(x_train_tensor.shape[1])
# model.weights
#define loop

#define optimoizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
for epoch in range(epochs):
    
    
    

    #forward pass
    y_pred=model(x_train_tensor)
    # print(y_pred)


    #loss pass
    loss=loss_function(y_pred,y_train_tensor)
    # print(f'Epoch:{epoch+1},Loss:{loss.item()}')
    
    #cleargrads
    #backeard pass
    optimizer.zero_grad()
    loss.backward()
    
    
    #parameter update
    # with torch.no_grad():
        
    #     model.linear.weight-=learning_rate*model.linear.weight.grad
    #     model.linear.bias-=learning_rate*model.linear.bias.grad
    optimizer.step()
    #zero gradients
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    
    #print loss in each epocj
    print(f'Epoch:{epoch+1},Loss:{loss.item()}')

Epoch:1,Loss:0.6571404933929443
Epoch:2,Loss:0.4850862920284271
Epoch:3,Loss:0.39875420928001404
Epoch:4,Loss:0.3471888303756714
Epoch:5,Loss:0.31245940923690796
Epoch:6,Loss:0.287218302488327
Epoch:7,Loss:0.2678879201412201
Epoch:8,Loss:0.25250759720802307
Epoch:9,Loss:0.2399086356163025
Epoch:10,Loss:0.22934912145137787
Epoch:11,Loss:0.22033429145812988
Epoch:12,Loss:0.21252097189426422
Epoch:13,Loss:0.20566317439079285
Epoch:14,Loss:0.19957976043224335
Epoch:15,Loss:0.19413405656814575
Epoch:16,Loss:0.18922097980976105
Epoch:17,Loss:0.18475820124149323
Epoch:18,Loss:0.18068024516105652
Epoch:19,Loss:0.17693431675434113
Epoch:20,Loss:0.17347726225852966
Epoch:21,Loss:0.17027348279953003
Epoch:22,Loss:0.1672932356595993
Epoch:23,Loss:0.16451160609722137
Epoch:24,Loss:0.16190730035305023
Epoch:25,Loss:0.15946221351623535

#

In [95]:
model.linear.weight

Parameter containing:
tensor([[ 0.3171,  0.1343,  0.3765,  0.1837,  0.1139,  0.0125,  0.0379,  0.3534,
         -0.0270,  0.0124,  0.2723,  0.0792,  0.2257,  0.1542, -0.1064, -0.1226,
          0.0475, -0.0376,  0.0154, -0.1294,  0.1577,  0.2666,  0.1707,  0.2049,
          0.0415,  0.3180,  0.1899,  0.3731,  0.3032,  0.1882]],
       requires_grad=True)

In [96]:
model.linear.bias

Parameter containing:
tensor([-0.2359], requires_grad=True)

## Evaluation

In [97]:
#model evlauation
with torch.no_grad():
    y_pred=model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
  
    
print(y_pred)

Accuracy: 0.8508771657943726
tensor([[0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])