##  Trainning Pipeline

#### Today objective
1. building a simple neural network* 
2. dataset:- Breast canceer dataset*
3. main goal:- code to create a neural network

### Steps to Follow

1. Load the dataset
2. Basic Preprocessing
3. Training Process
   1. Creating the model
   2. Forward pass
   3. Loss calculation
   4. Backpropagation
   5. Parameter update
4. Model Evaluation

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.size

18777

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
#train test split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [8]:
#scaling
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

In [9]:
x_train

array([[-0.70298015,  1.21905289, -0.71508645, ..., -0.99879299,
         0.57094012, -0.89774295],
       [-0.18574726,  0.07157408, -0.23881565, ...,  0.037583  ,
        -0.02096605, -0.55014412],
       [-0.29315081, -0.00398009, -0.37131821, ..., -1.56456111,
        -0.75262785, -1.15094593],
       ...,
       [-0.06421167, -0.56591416, -0.02878064, ...,  0.79214415,
         1.20559506,  1.23726901],
       [-0.28467159, -0.8539644 , -0.24743037, ..., -0.62181791,
         0.47228909, -0.09926514],
       [-0.09530217,  1.04905603, -0.128055  , ..., -0.80159898,
        -0.38433067, -1.1331773 ]], shape=(455, 30))

In [10]:
y_train

305    B
171    M
58     B
515    B
493    B
      ..
156    M
402    B
215    M
20     B
243    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
#Label Encoding
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [12]:
y_train

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0])

In [13]:
type(y_train)

numpy.ndarray

In [14]:
y_test

array([0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1])

In [15]:
# Numpy arrays to Pytorch tensors
x_train_tensor=torch.from_numpy(x_train).float()
x_test_tensor=torch.from_numpy(x_test).float()

y_train_tensor=torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor=torch.from_numpy(y_test).float().unsqueeze(1)

In [16]:

from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
    def __len__(self):  
        return self.features.shape[0]
    
    def __getitem__(self,index):
        return self.features[index],self.labels[index]

In [17]:
train_dataset=CustomDataset(x_train_tensor,y_train_tensor)
test_dataset=CustomDataset(x_test_tensor,y_test_tensor)

In [18]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

In [19]:
x_train_tensor

tensor([[-0.7030,  1.2191, -0.7151,  ..., -0.9988,  0.5709, -0.8977],
        [-0.1857,  0.0716, -0.2388,  ...,  0.0376, -0.0210, -0.5501],
        [-0.2932, -0.0040, -0.3713,  ..., -1.5646, -0.7526, -1.1509],
        ...,
        [-0.0642, -0.5659, -0.0288,  ...,  0.7921,  1.2056,  1.2373],
        [-0.2847, -0.8540, -0.2474,  ..., -0.6218,  0.4723, -0.0993],
        [-0.0953,  1.0491, -0.1281,  ..., -0.8016, -0.3843, -1.1332]])

# defineing the model

In [20]:
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()
        
        
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

    # def loss_function(self, y_pred, y):
        
        # Clamp predictions to avoid log(0)
        # epsilon = 1e-7
        # y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    
        # # Calculate loss
        # loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        # # print(f"epoch {loss}")
        # return loss

In [21]:
loss_function=nn.BCELoss()

### Impotrant Parameter

In [22]:
learning_rate=0.1
epochs=25

## Trainign pipeline

In [23]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [24]:
x_train_tensor

tensor([[-0.7030,  1.2191, -0.7151,  ..., -0.9988,  0.5709, -0.8977],
        [-0.1857,  0.0716, -0.2388,  ...,  0.0376, -0.0210, -0.5501],
        [-0.2932, -0.0040, -0.3713,  ..., -1.5646, -0.7526, -1.1509],
        ...,
        [-0.0642, -0.5659, -0.0288,  ...,  0.7921,  1.2056,  1.2373],
        [-0.2847, -0.8540, -0.2474,  ..., -0.6218,  0.4723, -0.0993],
        [-0.0953,  1.0491, -0.1281,  ..., -0.8016, -0.3843, -1.1332]])

In [ ]:
# model.parameters

<bound method Module.parameters of MySimpleNN(
  (linear): Linear(in_features=30, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)>

In [25]:
# create model 
model=MySimpleNN(x_train_tensor.shape[1])
# model.weights
#define loop

#define optimoizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
for epoch in range(epochs):
    
    
    

    #forward pass
    y_pred=model(x_train_tensor)
    # print(y_pred)


    #loss pass
    loss=loss_function(y_pred,y_train_tensor)
    # print(f'Epoch:{epoch+1},Loss:{loss.item()}')
    
    #cleargrads
    #backeard pass
    optimizer.zero_grad()
    loss.backward()
    
    
    #parameter update
    # with torch.no_grad():
        
    #     model.linear.weight-=learning_rate*model.linear.weight.grad
    #     model.linear.bias-=learning_rate*model.linear.bias.grad
    optimizer.step()
    #zero gradients
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    
    #print loss in each epocj
    print(f'Epoch:{epoch+1},Loss:{loss.item()}')

Epoch:1,Loss:0.600884735584259
Epoch:2,Loss:0.4873183071613312
Epoch:3,Loss:0.41749829053878784
Epoch:4,Loss:0.3701053559780121
Epoch:5,Loss:0.3356594741344452
Epoch:6,Loss:0.3093647360801697
Epoch:7,Loss:0.288539856672287
Epoch:8,Loss:0.27156952023506165
Epoch:9,Loss:0.25742289423942566
Epoch:10,Loss:0.245411217212677
Epoch:11,Loss:0.23505638539791107
Epoch:12,Loss:0.22601598501205444
Epoch:13,Loss:0.21803811192512512
Epoch:14,Loss:0.21093298494815826
Epoch:15,Loss:0.20455485582351685
Epoch:16,Loss:0.19878971576690674
Epoch:17,Loss:0.19354701042175293
Epoch:18,Loss:0.18875376880168915
Epoch:19,Loss:0.18435055017471313
Epoch:20,Loss:0.18028825521469116
Epoch:21,Loss:0.1765260398387909
Epoch:22,Loss:0.17302954196929932
Epoch:23,Loss:0.16976962983608246
Epoch:24,Loss:0.1667213886976242
Epoch:25,Loss:0.16386346518993378

#

In [29]:
model.linear.weight

Parameter containing:
tensor([[ 0.2707,  0.1583,  0.1055,  0.1590,  0.0274,  0.0509,  0.3315,  0.1313,
          0.0938, -0.0034,  0.2440, -0.0320,  0.3126,  0.2496, -0.0201, -0.0225,
         -0.0429,  0.0133,  0.0549, -0.0332,  0.3894,  0.3257,  0.4084,  0.3780,
          0.2333,  0.2348,  0.0120,  0.1086,  0.2548,  0.0329]],
       requires_grad=True)

In [30]:
model.linear.bias

Parameter containing:
tensor([-0.0655], requires_grad=True)

## Evaluation

In [31]:
#model evaluation usign test loader
model.eval()#set the model to evaluate model
accuracy_list=[]

with torch.no_grad():
    for batch_features,batch_labels in test_loader:
        #for4ward pass
        y_pred=model(batch_features)
        y_pred=(y_pred>0.8).float()
        
        #calcualte accuracy
        batch_accuracy=(y_pred.view(-1)==batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)
        
#calculate overall accuracxy
overall_accuracy=sum(accuracy_list)/len(accuracy_list)
print(f'accyuracy:{overall_accuracy:4f}')

accyuracy:0.535138

In [32]:
#model evlauation
with torch.no_grad():
    y_pred=model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
  
    
print(y_pred)

Accuracy: 0.8245614171028137
tensor([[0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]])