##  Trainning Pipeline

#### Today objective
1. building a simple neural network* 
2. dataset:- Breast canceer dataset*
3. main goal:- code to create a neural network

### Steps to Follow

1. Load the dataset
2. Basic Preprocessing
3. Training Process
   1. Creating the model
   2. Forward pass
   3. Loss calculation
   4. Backpropagation
   5. Parameter update
4. Model Evaluation

In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.size

18777

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [8]:
#train test split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [9]:
#scaling
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

In [10]:
x_train

array([[-0.5722476 , -0.37102357, -0.56901085, ..., -0.77907121,
         0.22332492, -0.72374276],
       [-1.19874609, -0.47434078, -1.18759065, ..., -0.8823266 ,
         0.12939406, -0.5587815 ],
       [-0.27364671,  0.27643093, -0.32443706, ..., -1.09447224,
        -0.34339126, -0.53174771],
       ...,
       [-0.66802525,  0.51980035, -0.70579253, ..., -1.1675734 ,
        -0.74103189, -1.00952849],
       [-1.23283167,  2.03511938, -1.23822028, ..., -0.99228292,
        -0.91636949, -0.65202047],
       [ 1.56303052,  0.53816785,  1.54722616, ...,  1.70088549,
         1.78257716, -0.26196157]], shape=(455, 30))

In [11]:
y_train

394    B
206    B
494    B
85     M
522    B
      ..
48     B
331    B
50     B
459    B
343    M
Name: diagnosis, Length: 455, dtype: object

In [12]:
#Label Encoding
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [13]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1])

In [14]:
type(y_train)

numpy.ndarray

In [15]:
y_test

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0])

In [16]:
# Numpy arrays to Pytorch tensors
x_train_tensor=torch.from_numpy(x_train).float()
x_test_tensor=torch.from_numpy(x_test).float()

y_train_tensor=torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor=torch.from_numpy(y_test).float().unsqueeze(1)

In [17]:

from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
    def __len__(self):  
        return self.features.shape[0]
    
    def __getitem__(self,index):
        return self.features[index],self.labels[index]

In [18]:
train_dataset=CustomDataset(x_train_tensor,y_train_tensor)
test_dataset=CustomDataset(x_test_tensor,y_test_tensor)

In [19]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

In [20]:
x_train_tensor

tensor([[-0.5722, -0.3710, -0.5690,  ..., -0.7791,  0.2233, -0.7237],
        [-1.1987, -0.4743, -1.1876,  ..., -0.8823,  0.1294, -0.5588],
        [-0.2736,  0.2764, -0.3244,  ..., -1.0945, -0.3434, -0.5317],
        ...,
        [-0.6680,  0.5198, -0.7058,  ..., -1.1676, -0.7410, -1.0095],
        [-1.2328,  2.0351, -1.2382,  ..., -0.9923, -0.9164, -0.6520],
        [ 1.5630,  0.5382,  1.5472,  ...,  1.7009,  1.7826, -0.2620]])

# defineing the model

In [21]:
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()
        
        
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

    # def loss_function(self, y_pred, y):
        
        # Clamp predictions to avoid log(0)
        # epsilon = 1e-7
        # y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    
        # # Calculate loss
        # loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        # # print(f"epoch {loss}")
        # return loss

In [22]:
loss_function=nn.BCELoss()

### Impotrant Parameter

In [23]:
learning_rate=0.1
epochs=25

## Trainign pipeline

In [24]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [25]:
x_train_tensor

tensor([[-0.5722, -0.3710, -0.5690,  ..., -0.7791,  0.2233, -0.7237],
        [-1.1987, -0.4743, -1.1876,  ..., -0.8823,  0.1294, -0.5588],
        [-0.2736,  0.2764, -0.3244,  ..., -1.0945, -0.3434, -0.5317],
        ...,
        [-0.6680,  0.5198, -0.7058,  ..., -1.1676, -0.7410, -1.0095],
        [-1.2328,  2.0351, -1.2382,  ..., -0.9923, -0.9164, -0.6520],
        [ 1.5630,  0.5382,  1.5472,  ...,  1.7009,  1.7826, -0.2620]])

In [26]:
# create model 
model=MySimpleNN(x_train_tensor.shape[1])
# model.weights
#define loop

#define optimoizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
for epoch in range(epochs):
    
    
    

    #forward pass
    y_pred=model(x_train_tensor)
    # print(y_pred)


    #loss pass
    loss=loss_function(y_pred,y_train_tensor)
    # print(f'Epoch:{epoch+1},Loss:{loss.item()}')
    
    #cleargrads
    #backeard pass
    optimizer.zero_grad()
    loss.backward()
    
    
    #parameter update
    # with torch.no_grad():
        
    #     model.linear.weight-=learning_rate*model.linear.weight.grad
    #     model.linear.bias-=learning_rate*model.linear.bias.grad
    optimizer.step()
    #zero gradients
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    
    #print loss in each epocj
    print(f'Epoch:{epoch+1},Loss:{loss.item()}')

Epoch:1,Loss:0.6641397476196289
Epoch:2,Loss:0.5076153874397278
Epoch:3,Loss:0.42545661330223083
Epoch:4,Loss:0.37505197525024414
Epoch:5,Loss:0.3401474356651306
Epoch:6,Loss:0.3140859007835388
Epoch:7,Loss:0.2936391234397888
Epoch:8,Loss:0.27702847123146057
Epoch:9,Loss:0.26318007707595825
Epoch:10,Loss:0.25140073895454407
Epoch:11,Loss:0.24121974408626556
Epoch:12,Loss:0.2323043942451477
Epoch:13,Loss:0.22441190481185913
Epoch:14,Loss:0.21736037731170654
Epoch:15,Loss:0.21101044118404388
Epoch:16,Loss:0.2052532285451889
Epoch:17,Loss:0.20000240206718445
Epoch:18,Loss:0.19518828392028809
Epoch:19,Loss:0.19075413048267365
Epoch:20,Loss:0.18665312230587006
Epoch:21,Loss:0.18284621834754944
Epoch:22,Loss:0.17930059134960175
Epoch:23,Loss:0.1759883463382721
Epoch:24,Loss:0.17288567125797272
Epoch:25,Loss:0.16997206211090088

#

In [27]:
model.linear.weight

Parameter containing:
tensor([[ 0.3993,  0.2583,  0.4019,  0.1175, -0.0153,  0.2476,  0.1269,  0.1142,
          0.1580, -0.1230,  0.1983, -0.0615,  0.0926,  0.0635, -0.0035, -0.1343,
          0.0604,  0.1451, -0.0773, -0.0306,  0.1989,  0.0350,  0.1618,  0.3933,
          0.2782, -0.0319,  0.3310,  0.2955,  0.1227,  0.1495]],
       requires_grad=True)

In [28]:
model.linear.bias

Parameter containing:
tensor([-0.2667], requires_grad=True)

## Evaluation

In [29]:
#model evaluation usign test loader
model.eval()#set the model to evaluate model
accuracy_list=[]

with torch.no_grad():
    for batch_features,batch_labels in test_loader:
        #for4ward pass
        y_pred=model(batch_features)
        y_pred=(y_pred>0.8).float()
        
        #calcualte accuracy
        batch_accuracy=(y_pred.view(-1)==batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)
        
#calculate overall accuracxy
overall_accuracy=sum(accuracy_list)/len(accuracy_list)
print(f'accyuracy:{overall_accuracy:4f}')

accyuracy:0.551776

In [30]:
#model evlauation
with torch.no_grad():
    y_pred=model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
  
    
print(y_pred)

Accuracy: 0.8157894611358643
tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.]])