##  Trainning Pipeline

#### Today objective
1. building a simple neural network* 
2. dataset:- Breast canceer dataset*
3. main goal:- code to create a neural network

### Steps to Follow

1. Load the dataset
2. Basic Preprocessing
3. Training Process
   1. Creating the model
   2. Forward pass
   3. Loss calculation
   4. Backpropagation
   5. Parameter update
4. Model Evaluation

In [30]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [31]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [32]:
df.size

18777

In [33]:
df.shape

(569, 33)

In [34]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [35]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [36]:
#train test split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [37]:
#scaling
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

In [38]:
x_train

array([[ 0.61565039, -0.74509342,  0.62307115, ...,  0.15389062,
         0.41362794,  0.30331263],
       [-1.12921722, -1.06070248, -1.09055977, ..., -1.13365137,
        -0.74326782,  0.04813911],
       [-0.30549799, -1.26259945, -0.38502245, ..., -1.21637396,
        -1.26942208, -0.98336741],
       ...,
       [-1.12921722, -1.63854554, -1.10979004, ..., -0.7334694 ,
         0.0660765 , -0.36597724],
       [-0.68930982, -0.39931585, -0.67646791, ..., -0.21393492,
        -0.6724703 , -0.34705547],
       [ 1.78480026,  2.08146419,  1.68714621, ...,  0.72928574,
        -0.52122107, -0.95255196]], shape=(455, 30))

In [39]:
y_train

375    B
345    B
309    B
260    M
377    B
      ..
401    B
182    M
390    B
530    B
565    M
Name: diagnosis, Length: 455, dtype: object

In [40]:
#Label Encoding
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [41]:
y_train

array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1])

In [42]:
type(y_train)

numpy.ndarray

In [43]:
y_test

array([0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0])

In [44]:
# Numpy arrays to Pytorch tensors
x_train_tensor=torch.from_numpy(x_train).float()
x_test_tensor=torch.from_numpy(x_test).float()

y_train_tensor=torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor=torch.from_numpy(y_test).float().unsqueeze(1)

In [45]:

from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self,index):
        return self.features[index],self.labels[index]

In [46]:
train_dataset=CustomDataset(x_train_tensor,y_train_tensor)
test_dataset=CustomDataset(x_test_tensor,y_test_tensor)

In [47]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

In [48]:
x_train_tensor

tensor([[ 0.6157, -0.7451,  0.6231,  ...,  0.1539,  0.4136,  0.3033],
        [-1.1292, -1.0607, -1.0906,  ..., -1.1337, -0.7433,  0.0481],
        [-0.3055, -1.2626, -0.3850,  ..., -1.2164, -1.2694, -0.9834],
        ...,
        [-1.1292, -1.6385, -1.1098,  ..., -0.7335,  0.0661, -0.3660],
        [-0.6893, -0.3993, -0.6765,  ..., -0.2139, -0.6725, -0.3471],
        [ 1.7848,  2.0815,  1.6871,  ...,  0.7293, -0.5212, -0.9526]])

# defineing the model

In [ ]:
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()
        
        
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

    # def loss_function(self, y_pred, y):
        
        # Clamp predictions to avoid log(0)
        # epsilon = 1e-7
        # y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    
        # # Calculate loss
        # loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        # # print(f"epoch {loss}")
        # return loss

In [50]:
loss_function=nn.BCELoss()

### Impotrant Parameter

In [51]:
learning_rate=0.1
epochs=25

## Trainign pipeline

In [52]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [53]:
# create model 
model=MySimpleNN(x_train_tensor.shape[1])
# model.weights
#define loop

#define optimoizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
for epoch in range(epochs):
    
    
    

    #forward pass
    y_pred=model(x_train_tensor)
    # print(y_pred)


    #loss pass
    loss=loss_function(y_pred,y_train_tensor)
    # print(f'Epoch:{epoch+1},Loss:{loss.item()}')
    
    #cleargrads
    #backeard pass
    optimizer.zero_grad()
    loss.backward()
    
    
    #parameter update
    # with torch.no_grad():
        
    #     model.linear.weight-=learning_rate*model.linear.weight.grad
    #     model.linear.bias-=learning_rate*model.linear.bias.grad
    optimizer.step()
    #zero gradients
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    
    #print loss in each epocj
    print(f'Epoch:{epoch+1},Loss:{loss.item()}')

Epoch:1,Loss:0.8692787885665894
Epoch:2,Loss:0.5930761694908142
Epoch:3,Loss:0.4586963653564453
Epoch:4,Loss:0.38691768050193787
Epoch:5,Loss:0.34198057651519775
Epoch:6,Loss:0.31063127517700195
Epoch:7,Loss:0.2871899902820587
Epoch:8,Loss:0.26881200075149536
Epoch:9,Loss:0.25390005111694336
Epoch:10,Loss:0.2414807677268982
Epoch:11,Loss:0.23092374205589294
Epoch:12,Loss:0.22180083394050598
Epoch:13,Loss:0.2138100117444992
Epoch:14,Loss:0.20673151314258575
Epoch:15,Loss:0.2004012167453766
Epoch:16,Loss:0.19469380378723145
Epoch:17,Loss:0.18951165676116943
Epoch:18,Loss:0.18477754294872284
Epoch:19,Loss:0.18042944371700287
Epoch:20,Loss:0.17641681432724
Epoch:21,Loss:0.17269806563854218
Epoch:22,Loss:0.1692386120557785
Epoch:23,Loss:0.1660093516111374
Epoch:24,Loss:0.1629856526851654
Epoch:25,Loss:0.16014644503593445

#

In [54]:
model.linear.weight

Parameter containing:
tensor([[ 0.1232,  0.2763,  0.1770,  0.0863,  0.0747,  0.0969,  0.2272,  0.1003,
          0.2653,  0.0078,  0.2914, -0.0785,  0.3521,  0.1187, -0.1796, -0.0148,
         -0.0356,  0.1908, -0.0738, -0.1063,  0.3461,  0.3387,  0.4566,  0.1382,
          0.1319,  0.1601,  0.1821,  0.1525,  0.0874,  0.0919]],
       requires_grad=True)

In [55]:
model.linear.bias

Parameter containing:
tensor([-0.2987], requires_grad=True)

## Evaluation

In [57]:
#model evaluation usign test loader
model.eval()#set the model to evaluate model
accuracy_list=[]

with torch.no_grad():
    for batch_features,batch_labels in test_loader:
        #for4ward pass
        y_pred=model(batch_features)
        y_pred=(y_pred>0.8).float()
        
        #calcualte accuracy
        batch_accuracy=(y_pred.view(-1)==batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)
        
#calculate overall accuracxy
overall_accuracy=sum(accuracy_list)/len(accuracy_list)
print(f'accyuracy:{overall_accuracy:4f}')

accyuracy:0.560788

In [56]:
#model evlauation
with torch.no_grad():
    y_pred=model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
  
    
print(y_pred)

Accuracy: 0.8333333134651184
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]])