##  Trainning Pipeline

#### Today objective
1. building a simple neural network* 
2. dataset:- Breast canceer dataset*
3. main goal:- code to create a neural network

### Steps to Follow

1. Load the dataset
2. Basic Preprocessing
3. Training Process
   1. Creating the model
   2. Forward pass
   3. Loss calculation
   4. Backpropagation
   5. Parameter update
4. Model Evaluation

In [3]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.size

18777

In [6]:
df.shape

(569, 33)

In [7]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [8]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [9]:
#train test split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [10]:
#scaling
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

In [11]:
x_train

array([[-0.47213179,  0.13390494, -0.47262465, ..., -0.58207524,
        -0.33320693, -0.31083127],
       [ 0.56527438,  0.31632726,  0.66383245, ...,  1.41127839,
         1.3094374 ,  1.69372632],
       [ 0.35044367,  0.79662907,  0.33936512, ...,  0.50320352,
        -0.54074965, -0.8240331 ],
       ...,
       [ 0.72357069,  0.20548838,  0.62276064, ..., -0.41293299,
         2.87163881, -0.38814052],
       [ 1.54331943,  1.31387717,  1.46884001, ...,  0.48799289,
        -0.96387939, -1.22812471],
       [-0.79437784,  1.79417898, -0.82871728, ..., -1.4250486 ,
        -0.06935417, -0.68202533]], shape=(455, 30))

In [12]:
y_train

301    B
17     M
91     M
103    B
156    M
      ..
10     M
79     B
489    M
451    M
231    B
Name: diagnosis, Length: 455, dtype: object

In [13]:
#Label Encoding
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [14]:
y_train

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0])

In [40]:
type(y_train)

numpy.ndarray

In [15]:
y_test

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1])

In [16]:
# Numpy arrays to Pytorch tensors
x_train_tensor=torch.from_numpy(x_train)
x_test_tensor=torch.from_numpy(x_test)

y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [17]:
x_train_tensor

tensor([[-0.4721,  0.1339, -0.4726,  ..., -0.5821, -0.3332, -0.3108],
        [ 0.5653,  0.3163,  0.6638,  ...,  1.4113,  1.3094,  1.6937],
        [ 0.3504,  0.7966,  0.3394,  ...,  0.5032, -0.5407, -0.8240],
        ...,
        [ 0.7236,  0.2055,  0.6228,  ..., -0.4129,  2.8716, -0.3881],
        [ 1.5433,  1.3139,  1.4688,  ...,  0.4880, -0.9639, -1.2281],
        [-0.7944,  1.7942, -0.8287,  ..., -1.4250, -0.0694, -0.6820]],
       dtype=torch.float64)

# defineing the model

In [47]:
class MySimpleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
    def forward(self,x):
        z=torch.matmul(x,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    def loss_function(self, y_pred, y):
        
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        # print(f"epoch {loss}")
        return loss

### Impotrant Parameter

In [19]:
learning_rate=0.1
epochs=25

## Trainign pipeline

In [48]:
# create model 
model=MySimpleNN(x_train_tensor)
model.weights
#define loop
for epoch in range(epochs):
    
    
    

    #forward pass
    y_pred=model.forward(x_train_tensor)
    # print(y_pred)


    #loss pass
    loss=model.loss_function(y_pred,y_train_tensor)
    # print(f'Epoch:{epoch+1},Loss:{loss.item()}')
    
    #backeard pass
    loss.backward()
    
    
    #parameter update
    with torch.no_grad():
        
        model.weights-=learning_rate*model.weights.grad
        model.bias-=learning_rate*model.bias.grad
    #zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    #print loss in each epocj
    print(f'Epoch:{epoch+1},Loss:{loss.item()}')

Epoch:1,Loss:2.981908544823921
Epoch:2,Loss:2.83651647030282
Epoch:3,Loss:2.689296858176911
Epoch:4,Loss:2.5381931634926884
Epoch:5,Loss:2.3804274228859468
Epoch:6,Loss:2.2222424425010288
Epoch:7,Loss:2.0636366187616977
Epoch:8,Loss:1.9012541063371382
Epoch:9,Loss:1.7434302548281015
Epoch:10,Loss:1.5895936015058798
Epoch:11,Loss:1.4422175939615722
Epoch:12,Loss:1.307706781615881
Epoch:13,Loss:1.1879959171865164
Epoch:14,Loss:1.0847666844817465
Epoch:15,Loss:0.9990773818755821
Epoch:16,Loss:0.9309057340527902
Epoch:17,Loss:0.87883774768161
Epoch:18,Loss:0.8403036993568012
Epoch:19,Loss:0.8122666540986314
Epoch:20,Loss:0.7918519873302561
Epoch:21,Loss:0.7767037776227977
Epoch:22,Loss:0.7650906240728154
Epoch:23,Loss:0.7558391709559658
Epoch:24,Loss:0.7481947936145317
Epoch:25,Loss:0.7416842898261888

#

In [28]:
model.weights

tensor([[ 0.3300],
        [ 0.1137],
        [ 0.3706],
        [-0.3554],
        [ 0.4025],
        [ 0.2198],
        [ 0.0813],
        [-0.5584],
        [ 0.2847],
        [ 0.0210],
        [ 0.4909],
        [ 0.5229],
        [-0.1719],
        [ 0.4549],
        [ 0.0856],
        [ 0.2276],
        [-0.2534],
        [-0.4696],
        [ 0.1097],
        [-0.0087],
        [ 0.4256],
        [-0.2168],
        [-0.1289],
        [-0.4980],
        [-0.0131],
        [ 0.1076],
        [ 0.3655],
        [-0.4165],
        [ 0.2230],
        [-0.2332]], dtype=torch.float64, requires_grad=True)

In [29]:
model.bias

tensor([-0.1032], dtype=torch.float64, requires_grad=True)

## Evaluation

In [37]:
#model evlauation
with torch.no_grad():
    y_pred=model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
  
    
print(y_pred)

Accuracy: 0.6280394196510315
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])